name: nodejs

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    # create short commit SHA hash to label image with
    steps:
      - name: create short SHA
        id: create_short_sha
        run: |
          long=$GITHUB_SHA
          short=${long:0:6}
          echo "shortsha=$short" >> $GITHUB_ENV

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          labels: |
            email=ron@upmyjob.com
            commit=${{ env.shortsha }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs:latest